rodeo_control/app_core/urls.py
from django.urls import path
from app_core.views import general

app_name = 'app_core'
urlpatterns = [
    path('', general.index, name='index'),
    path('rodeo/<int:pk>/', general.rodeo, name='rodeo'),
    path('rodeo/<int:pk>/animales/', general.rodeo_animales, name='rodeo_animales'),
]

rodeo_control/rodeo_control/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_core.urls', namespace='app_core')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rodeo_control/app_core/models.py
from django.db import models

# Create your models here.
class AuditoriaFecha(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Finca(AuditoriaFecha):
    nombre = models.CharField("Nombre de la Finca", max_length=60, default='', null=True, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Finca'
        verbose_name_plural = 'Fincas'

    def __str__(self):
        return "{0}".format(str(self.nombre))
    
class Rodeo(AuditoriaFecha):
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE)
    nombre = models.CharField("Nombre del Rodeo", max_length=60, default='', null=True, blank=True)
    fecha  = models.DateField("Fecha de creación", null=True, blank=True)
    descripcion = models.TextField("Descripción", null=True, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Rodeo'
        verbose_name_plural = 'Rodeos'

    def __str__(self):
        return "{0}".format(str(self.nombre))
    
class Animal(AuditoriaFecha):
    rodeo = models.ForeignKey(Rodeo, on_delete=models.CASCADE)
    numero = models.IntegerField("Número del animal", blank=True, null=True)
    fecha  = models.DateField("Fecha de nacimiento", null=True, blank=True)
    observacion = models.TextField("Observaciones", null=True, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Animal'
        verbose_name_plural = 'Animales'

    def __str__(self):
        return "{0} - {1}".format(str(self.rodeo.nombre), str(self.numero))

rodeo_control/app_core/views.py
from django.shortcuts import render

# Create your views here.

rodeo_control/app_core/views/general.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.urls import reverse
from datetime import datetime
from app_core.models import Finca, Rodeo, Animal

def index(request):
  rodeos = Rodeo.objects.all()

  context = {
    'rodeos':rodeos,
  }

  if request.method == 'POST':
    nombre = request.POST.get('nombre', '')
    descripcion = request.POST.get('descripcion', '')

    finca = Finca.objects.all().first()
    fecha_actual = datetime.now()
    Rodeo.objects.create(finca=finca, nombre=nombre, fecha=fecha_actual, descripcion=descripcion)
    
    return redirect(reverse('app_core:index'), context)

  return render(request, 'app_core/general/index.html', context)

def rodeo(request, pk):
  rodeo = get_object_or_404(Rodeo, pk=pk)
  animales = Animal.objects.filter(rodeo=pk)

  context = {
    'rodeo':rodeo,
    'animales':animales,
  }

  if request.method == 'POST':
    nombre_rodeo = request.POST.get('nombre_rodeo', '')
    descripcion_rodeo = request.POST.get('descripcion_rodeo', '')
    numero = request.POST.get('numero', '')
    fecha = request.POST.get('fecha', '')
    observacion = request.POST.get('observacion', '')
    animal_id = request.POST.get('animal_id', '')
    add_or_edit_or_delete = request.POST.get('add_or_edit_or_delete', '')

    if add_or_edit_or_delete == '0':
      Animal.objects.create(rodeo=rodeo, numero=numero, fecha=fecha, observacion=observacion)
    elif add_or_edit_or_delete == '1':
      Animal.objects.filter(pk=animal_id).update(rodeo=rodeo, numero=numero, fecha=fecha, observacion=observacion)
    elif add_or_edit_or_delete == '2':
      Animal.objects.filter(pk=animal_id).delete()
    elif add_or_edit_or_delete == '3':
      Rodeo.objects.filter(pk=pk).update(nombre=nombre_rodeo, descripcion=descripcion_rodeo)
    elif add_or_edit_or_delete == '4':
      Rodeo.objects.filter(pk=pk).delete()
      rodeos = Rodeo.objects.all()
      context = {
        'rodeos':rodeos,
      }
      return redirect(reverse('app_core:index'), context)
    
    return redirect(reverse('app_core:rodeo', args=[rodeo.id]), context)
  
  return render(request, 'app_core/general/rodeo.html', context)

def rodeo_animales(request, pk):
  animales = Animal.objects.filter(rodeo=pk).values('id', 'numero', 'fecha', 'observacion')
  data = list(animales)

  return JsonResponse(data, safe=False)
  

rodeo_control/templates/app_core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Themes Industry">
    <!-- description -->
    <meta name="description" content="MegaOne is a highly creative, modern, visually stunning and Bootstrap responsive multipurpose agency and HTML5 template with 14 ready home page demos.">
    <!-- keywords -->
    <meta name="keywords" content="creative, modern, clean, bootstrap responsive, html5, css3, portfolio, blog, agency, templates, multipurpose, one page, corporate, start-up, studio, branding, designer, freelancer, carousel, parallax, photography, personal, masonry, grid, faq">
    <!-- Page Title -->
    <title>{% block head_title %}RodeoControl | {% endblock head_title %}</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'app_core/blog/img/favicon.ico' %}">
    <!-- Bundle -->
    <link rel="stylesheet" href="{% static 'app_core/vendor/css/bundle.min.css' %}">
    <!-- Plugin Css -->
    <link rel="stylesheet" href="{% static 'app_core/vendor/css/cubeportfolio.min.css' %}">
    <link rel="stylesheet" href="{% static 'app_core/blog/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'app_core/blog/css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'app_core/blog/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'app_core/blog/css/line-awesome.min.css' %}">
    <!-- Style Sheet -->
    <link rel="stylesheet" href="{% static 'app_core/vendor/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'app_core/blog/css/style.css' %}">

    <style>
        .mi-h1 {
            font-family: 'Montserrat' , sans-serif;
            font-size: 90px;
            letter-spacing: 4px;
            font-weight: bold;
        }

        @media only screen and (max-width: 768px) {
            .mi-h1 {
                font-family: 'Montserrat' , sans-serif;
                font-size: 50px;
                letter-spacing: 0px;
                font-weight: bold;
            }
        }
    </style>

    {% block extra_styles %} {% endblock extra_styles %}
</head>


<body data-spy="scroll" data-target=".navbar" data-offset="150">

<!-- start preloader -->
    {% include 'app_core/general/snippets/base/preloader.html' %}
<!-- end preloader -->

{% block content %} {% endblock content %}

<!-- JavaScript -->
<script src="{% static 'app_core/vendor/js/bundle.min.js' %}"></script>

<!-- Plugin Js -->
<script src="{% static 'app_core/vendor/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'app_core/vendor/js/jquery.cubeportfolio.min.js' %}"></script>
<!-- custom script -->
<script src="{% static 'app_core/blog/js/jquery.fancybox.js' %}"></script>
<script src="{% static 'app_core/blog/js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'app_core/blog/js/mediaelement-and-player.min.js' %}"></script>
<script src="{% static 'app_core/blog/js/wow.min.js' %}"></script>
<script src="{% static 'app_core/vendor/js/parallaxie.min.js' %}"></script>
<script src="{% static 'app_core/blog/js/script.js' %}"></script>

{% block extra_javascript %} {% endblock extra_javascript %}
</body>
</html>

rodeo_control/templates/app_core/general/index.html
{% extends "app_core/base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} Inicio{% endblock head_title %}

{% block content %}

    <header>
        <!-- start logo -->
            {% include 'app_core/general/snippets/index/logo.html' %}
        <!-- end logo -->

        <!-- start menu -->
            <!-- {% include 'app_core/general/snippets/menu.html' %} -->
        <!-- end menu -->
    </header>

    <!-- start banner -->
    {% include 'app_core/general/snippets/index/banner.html' %}
    <!-- end banner -->

    <!-- start about -->
        {% include 'app_core/general/snippets/index/about.html' %}
    <!-- end about -->

    <!-- start portafolio -->
        {% include 'app_core/general/snippets/index/portafolio.html' %}
    <!-- end portafolio -->

    <!-- start footer -->
        {% include 'app_core/general/snippets/footer.html' %}
    <!-- end footer -->

    <!-- start Modal Agregar Rodeo -->
        {% include 'app_core/general/snippets/index/modal_agregar_rodeo.html' %}
    <!-- end Modal Agregar Rodeo -->

{% endblock content %}

{% block extra_javascript %}{% endblock extra_javascript %}

rodeo_control/templates/app_core/general/rodeo.html
{% extends "app_core/base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} Inicio{% endblock head_title %}

{% block extra_styles %}
<link rel="stylesheet" href="{% static 'app_core/vendor/css/jquery.fancybox.min.css' %}">
<link rel="stylesheet" href="{% static 'app_core/vendor/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'app_core/vendor/css/cubeportfolio.min.css' %}">
<link rel="stylesheet" href="{% static 'app_core/blog/css/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'app_core/blog/css/line-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'app_core/blog/css/mediaelementplayer.css' %}">
<link rel="stylesheet" href="{% static 'app_core/blog/css/mejs-controls.svg' %}">
<!-- DataTables -->
<link href="{% static 'app_core/vendor/DataTables/datatables.min.css' %}" rel="stylesheet">
<style>
    .boton-borrar {
        background-color: #fff; /* Fondo blanco o transparente */
        border: none; /* Sin borde */
        cursor: pointer;
    }
    .boton-editar {
        background-color: #fff; /* Fondo blanco o transparente */
        border: none; /* Sin borde */
        cursor: pointer;
    }
    .marco-div {
        width: 200px; /* Ancho del div */
        height: 100px; /* Altura del div */
        border: 2px solid #000; /* Establece un borde sólido de 2px en color negro */
        padding: 10px; /* Añade espacio interno al contenido del div */
        margin: 20px; /* Añade espacio externo alrededor del div */
    }
</style>
{% endblock extra_styles %}

{% block content %}

<!-- START NAVBAR SECTION -->
<header>
    <!-- start navbar -->
        {% include 'app_core/general/snippets/rodeo/navbar.html' %}
    <!-- end navbar -->

    <!-- start menu -->
        {% include 'app_core/general/snippets/menu.html' %}
    <!-- end menu -->
</header>

<div id="page_content">

    <!--HEADER IMAGE-->
    <section id="bg-blog-detail-img" class="bg-blog-detail-img">
        <div class="overlay"></div>
    </section>

    <!-- start Tabla Animales -->
        {% include 'app_core/general/snippets/rodeo/section_tabla_animales.html' %}
    <!-- end Tabla Animales -->

    <!-- start footer -->
        {% include 'app_core/general/snippets/footer.html' %}
    <!-- end footer -->

    <!-- start Modal Editar Rodeo -->
        {% include 'app_core/general/snippets/rodeo/modal_editar_rodeo.html' %}
    <!-- end Modal Editar Rodeo -->

    <!-- start Modal Eliminar Rodeo -->
        {% include 'app_core/general/snippets/rodeo/modal_eliminar_rodeo.html' %}
    <!-- end Modal Eliminar Rodeo -->

    <!-- start Modal Agregar Animal -->
        {% include 'app_core/general/snippets/rodeo/modal_agregar_animal.html' %}
    <!-- end Modal Agregar Animal -->

    <!-- start Modal Editar Animal -->
        {% include 'app_core/general/snippets/rodeo/modal_editar_animal.html' %}
    <!-- end Modal Editar Animal -->
    
    <!-- start Modal Eliminar Animal -->
        {% include 'app_core/general/snippets/rodeo/modal_eliminar_animal.html' %}
    <!-- end Modal Eliminar Animal -->

</div>

{% endblock content %}

{% block extra_javascript %}
<script src="{% static 'app_core/vendor/js/jquery.fancybox.min.js' %}"></script>
<!-- REVOLUTION JS FILES -->
<script src="{% static 'app_core/vendor/js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'app_core/vendor/js/jquery.themepunch.revolution.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'app_core/vendor/DataTables/datatables.min.js' %}"></script>

<script>
    $(document).ready(function() {
        // Evento para el select de editar o eliminar un rodeo y desplegar el respectivo modal
        $('#miSelect').change(function() {
            // Esta función se ejecutará cada vez que se seleccione una opción
            var opcionSeleccionada = $(this).val();
            var select = document.getElementById('miSelect');
            select.selectedIndex = 0;
            if (opcionSeleccionada == '3') {
                $('#editarRodeoModal').modal('show');
                // console.log('Opción seleccionada:', opcionSeleccionada);
            } else if (opcionSeleccionada == '4'){
                $('#eliminarRodeoModal').modal('show');
                // console.log('Opción seleccionada:', opcionSeleccionada);
            }
            
        });

        // Evento para eliminar un rodeo, se debe escribir la palabra BORRAR para activar el boton de eliminar
        function eliminarRodeoKeyUp() {
            var valorInput = document.getElementById('eliminar_rodeo_texto').value;
            var boton = document.getElementById('eliminar_rodeo_btn');

            if (valorInput === 'BORRAR') {
                boton.disabled = false;
            } else {
                boton.disabled = true;
            }
        };
        document.getElementById('eliminar_rodeo_texto').addEventListener('keyup', eliminarRodeoKeyUp);

        //Configuración de DataTable
        function pintarDatatable(dataResult, columns) {
            $("#animalesTabla").DataTable({
                data: dataResult,
                columnDefs: columns,
                responsive: true,
                aaSorting: [[0, 'asc']],
                dom: "lBfrtip",
                buttons: [
                    'copy', 'excel', 'pdf'
                ],
                lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Todos"]],
                pageLength: 100,
                columns: [
                    { "width": "24%" },
                    { "width": "25%" },
                    { "width": "50%" },
                    { "width": "1%" } 
                ],
                language: {
                    "sProcessing":    "Procesando...",
                    "sLengthMenu":    "Mostrar _MENU_ registros",
                    "sZeroRecords":   "No se encontraron resultados",
                    "sEmptyTable":    "Ningún dato disponible en esta tabla",
                    "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":   "",
                    "sSearch":        "Buscar:",
                    "sUrl":           "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "sInfoThousands": ",",
                    "sInfoEmpty": "Mostrando 0 a 0 de 0 registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sSearch": "Buscar:",
                    "oPaginate": {
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                },
                "footer": true, // Habilita el pie de tabla
                "initComplete": function(settings, json) {
                    // Crear el pie de tabla con las sumas, promedios, u otra información necesaria
                    $(this).append('<tfoot><tr><th>Número</th><th>Fecha</th><th>Observación</th><th>Acción</th></tr></tfoot>');
                }
            });
        };

        async function datos() {
            const data = await fetch("{% url 'app_core:rodeo_animales' rodeo.id %}")
                .then(value => value.json())
                .then(value => value)

            //targets: position
            //Aquí data:"key". Ver arriba
            //En "render: callback " puedes tranformar la data.
            const columns = [{
                    targets: 0,
                    title: "Número",
                    data: "numero"
                },
                {
                    targets: 1,
                    title: "Fecha",
                    data: "fecha",
                    render: function(data,type,r,m) {
                        // Si el tipo de renderizado es 'display', se mostrará en la tabla
                        if (type === 'display') {
                            // Extrae solo el año de la fecha
                            var year = data.substring(0, 4);
                            // Devuelve el año para mostrar en la tabla
                            return year;
                        }
                        // Si no es 'display', simplemente devuelve los datos sin modificar
                        return data;
                    }
                },
                {
                    targets: 2,
                    title: "Observación",
                    data: "observacion"
                },
                {
                    targets: 3,
                    title: "Acción",
                    data: null,
                    render : (data,type,r,m) => {
                        return (type == "display") 
                        ? `
                            <button type="button" 
                                class="boton-editar modificar" 
                                data-toggle="modal" 
                                data-target="#editarAnimalModal" 
                                data-animal_id="${data.id}" 
                                data-numero="${data.numero}" 
                                data-fecha="${data.fecha}" 
                                data-observacion="${data.observacion}" >
                                <i class="fas fa-edit"></i>
                            </button> 
                            
                            <button type="button" 
                                class="boton-borrar eliminar" 
                                data-toggle="modal" 
                                data-target="#eliminarAnimalModal" 
                                data-animal_id="${data.id}" 
                                data-numero="${data.numero}">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        `  
                        : null
                    }
                }
            ]
            pintarDatatable(data, columns)
        };
        datos()

        // Manejar el clic en el botón de editar
        $('#animalesTabla').on('click', '.modificar', function() {
            // Obtiene los datos del atributo de datos del botón
            var animal_id = $(this).data('animal_id');
            var numero = $(this).data('numero');
            var fecha = $(this).data('fecha');
            var observacion = $(this).data('observacion');
            // Muestra los datos en el modal
            $('#animalIdInput').val(animal_id);
            $('#numeroInput').val(numero);
            $('#fechaInput').val(fecha);
            $('#observacionInput').val(observacion);
        });

        // Manejar el clic en el botón de editar
        $('#animalesTabla').on('click', '.eliminar', function() {
            var numeroLabel = document.getElementById("numeroLabel");
            // Obtiene los datos del atributo de datos del botón
            var animal_id = $(this).data('animal_id');
            var numero = $(this).data('numero');
            // Muestra los datos en el modal
            $('#animalIdInputBorrar').val(animal_id);
            numeroLabel.textContent = numero;
        });
    });
    
</script>

{% endblock extra_javascript %}

rodeo_control/templates/app_core/general/snippets/base/preloader.html
<!--  PRELOADER  -->
<div class="loader-area">
    <div class='loader'>
        <div class='one'></div>
        <div class='two'></div>
        <div class='three'></div>
    </div>
</div>

rodeo_control/templates/app_core/general/snippets/footer.html
<section id="footer" class="footer" style="padding-top: 42px;">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <!-- <ul class="footer_ul">
                    <li class="footer_list"><i class="lab la-facebook-f"></i></li>
                    <li class="footer_list"><i class="lab la-twitter"></i></li>
                    <li class="footer_list"><i class="lab la-google-plus"></i></li>
                    <li class="footer_list"><i class="lab la-linkedin-in"></i></li>
                    <li class="footer_list"><i class="lab la-instagram"></i></li>
                    <li class="footer_list"><i class="las la-envelope"></i></li>
                </ul> -->
                <p class="info footer_text" style="padding-bottom: 30px;"><i class="far fa-copyright"></i> <script>document.write(new Date().getFullYear())</script> Todos los derechos reservados.</p>
            </div>
        </div>
    </div>
</section>

rodeo_control/templates/app_core/general/snippets/formulario.html
<div class="comment">

    <h1 class="comment_text text-black mt-6 mb-5">Write a comment</h1>
    <form>
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Name" required id="Name" name="Name">
                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group">
                    <input class="form-control" type="email" placeholder="Email" required id="email" name="email">
                </div>
            </div>

            <div class="col-12">
                <div class="form-group">
                    <span class="message-error error"></span>
                    <textarea class="form-control" rows="5" required id="comment" placeholder="Comment"></textarea>
                </div>
                <button type="submit" class="btn btn-large btn-primary padding_button w-100" id="submit_btn">SUBMIT REQUEST</button>
            </div>

        </div>
    </form>
</div>

rodeo_control/templates/app_core/general/snippets/index/about.html
<section id="about" class="about pt-5">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="about-text text-left d-flex">
                    <p class="verticle-text text-grey pt-2">sobre nosotros</p>
                    <h1 class="main-heading ml-3">HATO LA TRAVESADA</h1>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <p class="sub-heading text-grey">Bienvenidos a "Hato La Travesada", una próspera finca ganadera ubicada en los exuberantes llanos de Casanare, Colombia. Nos enorgullece presentarles nuestro hato dedicado a la cría de ganado, donde la tradición, la pasión por la ganadería y el respeto por la tierra se entrelazan para dar forma a una experiencia única en la producción ganadera.
                    <br><br>
                    En Hato La Travesada, nos dedicamos con compromiso y amor al arte de criar ganado, aprovechando las vastas extensiones de los llanos de Casanare, una región conocida por su belleza natural y su clima propicio para la ganadería. Nuestro compromiso con la calidad, la sostenibilidad y el bienestar animal guía cada aspecto de nuestras operaciones. </p>
            </div>
        </div>
    </div>
</section>

rodeo_control/templates/app_core/general/snippets/index/banner.html
<section id="banner-img" class="banner-img bg-banner-img">

    <div class="row no-gutters">
        <div class="col-12 col-md-5"></div>
        <div class="col-12 col-md-7">
            <div class="overlay"></div>
            <div class="row no-gutters height1">
                <div class="col-2 d-flex justify-content-center align-items-center">
                    <p class="verticle-text text-white padding-vert">Donde la pasión por el ganado se cría con cada amanecer</p>
                </div>
                <div class="col-10 d-flex  align-items-center">
                    <h1 class="text-white mi-h1">HATO<br>LA<br>TRAVESADA<br></h1>
                </div>
            </div>
        </div>
    </div>
</section>

rodeo_control/templates/app_core/general/snippets/index/logo.html
{% load static %}

<nav id="my-nav" class="navbar navbar-expand-lg navbar-light rounded-bar sidemenu-nav">

    <div class="logo width-logo1">
        <a href="index-blog.html"><img src="{% static 'app_core/blog/img/logo.png' %}" alt="Logo Img"></a>
    </div>
    <!-- <div class="menu-btn ml-auto">
        <span></span>
        <span></span>
        <span></span>
    </div> -->

</nav>

rodeo_control/templates/app_core/general/snippets/index/modal_agregar_rodeo.html
<!-- Modal -->
<div class="modal fade" id="agregarRodeoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Nuevo Rodeo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="formAgregarRodeo" method="POST" action="">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <input class="form-control" type="text" placeholder="Nombre" required id="nombre" name="nombre">
                            </div>
                        </div>
            
                        <div class="col-12">
                            <div class="form-group">
                                <span class="message-error error"></span>
                                <textarea class="form-control" rows="5" id="descripcion" placeholder="Descripcion" name="descripcion"></textarea>
                            </div>
                            <button type="submit" class="btn btn-large btn-primary padding_button w-100" id="submit_btn">GUARDAR</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

rodeo_control/templates/app_core/general/snippets/index/portafolio.html
{% load static %}

<section id="portfolio" class="portfolio" style="padding-top: 45px;">
    <div class="container">

        <div style="padding-bottom: 30px; display: flex; justify-content: center; align-items: center;">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#agregarRodeoModal">
                AGREGAR RODEO
            </button>
        </div>

        <div id="js-grid-masonry-projects" class="cbp cbp-l-grid-masonry-projects">

            {% for rodeo in rodeos %}
                <div class="cbp-item">
                    <div class="cbp-caption">
                        
                        <!--  DESCOMENTAR LA SIGUIENTE SECCION PARA PONERLE FOTOSO A LOS RODEOS EN EL INDEX  -->

                        <div class="cbp-caption-defaultWrap">
                            <img src="{% static 'app_core/blog/img/portfolioS9.jpg' %}" alt="">

                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignCenter">
                                <div class="cbp-l-caption-body">
                                    <a href="{% url 'app_core:rodeo' rodeo.id %}" class="btn blog-btn cbp-l-caption-buttonLeft">READ MORE</a>
                                </div>
                            </div>
                        </div>

                        <!--  DESCOMENTAR LA SECCION ANTERIOR PARA PONERLE FOTOSO A LOS RODEOS EN EL INDEX  -->

                    </div>
                    <div class="portfolio-text">
                        <p class="portfolio-vert text-grey" style="font-size: 8px;">La Travesada</p>
                        <a class="text-black" href="{% url 'app_core:rodeo' rodeo.id %}"><h2 class="heading ml-3">{{rodeo.nombre}}</h2></a>
                        <p class="date text-grey">{{rodeo.date_created}}</p>

                        <div class="horizontal-line"></div>
                        <p class="sub-heading text-grey mt-3">{{rodeo.descripcion}}


                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
</section>